### ISSUE TITLE
How to use password ?

### ISSUE THREAD

**Issue by spihiker** [fetlife/redis-analyzer#2]
How to use password for auth? Thanks.

**Comment by reneklacan** [comment]
@spihiker `redis-analyzer -u user:password@host:port` should work, let me know if you have issues with that

**Comment by spihiker** [comment]
When I exectued  by redis-analyzer -u user:password@host:port. It work well.If don't configure username, redis-analyzer -u :password@host:port:password@host:port can also work.
  Thank you very much.
